### ISSUE TITLE
language choice

### ISSUE THREAD

**Issue by bayprogrammer** [glavo-project/glavo#3]
So... I'm wanting to get back to this. I'm not so keen on Ruby anymore. @DonnieWest mind if I start hacking on this a bit in a different language? (I'm thinking going back to Clojure, or using JavaScript or Python). Not super concerned about compat with the Sword libs, but if we go back to Clojure we would have easy access to JSword. Let me know if you have any thoughts.

**Comment by DonnieWest** [comment]
I'm concerned about Sword libs just because of the easy access to Bibles
and an organization that has already dealt with all the legal aspects
there: if you want Bibles outside of the public domain there's quite a
process.

That being said - go for it! JavaScript, Python, Scala, Ruby, Java I can
immediately help with if you choose them, I'm also mildly interested in Go
as a future language and I know off the top of my head the tooling is there

**Comment by bayprogrammer** [comment]
> I'm concerned about Sword libs just because of the easy access to Bibles

Wanting to use the bibles published in the sword format do not require the use of the Swords libs though right? Sword libs speed things up, but I'm not sure that not using them removes access to freely distributed books in that format (perhaps I'm wrong there?)

**Comment by bayprogrammer** [comment]
Just found this:

> Whilst our software is open source, our module file format is proprietary,
> in the sense that we see no need to document it and certainly no need to
> stick to it.

(source: http://www.crosswire.org/wiki/File_Formats#SWORD_modules)

That bothers me, actually.

**Comment by DonnieWest** [comment]
I'm available to chat if you want to work out a mutually agreeable
solution. Maybe sword isn't the way we want to go :-P

**Comment by bayprogrammer** [comment]
Here's my current thoughts: Sword should not be a core dependency. I would rather focus on building a clean experience that is focused on aiding Christians in utilizing freely accessible resources (that can be still used 100 years from now) first. But Crosswire has done good work in making many useful resources available in their proprietary format, and the tools to access that format are FLOSS. We would provide optional modules to Glavo which would allow importing SWORD modules into the Glavo system for those users who wish to make use of them, without being encumbered by Crosswire's legacy format. Sound reasonable to you?

I'll try to hop on chat in a bit, happy to chat there too, but let's document our decisions here for the sake of all the future contributors! :-D

**Comment by DonnieWest** [comment]
I agree with all of the principles espoused. I'd argue that the steps we should take are:

1. Create a wrapper for SWORD
2. Create the project with an architecture in place with a reliance on wrapper
3. Create SWORD alternative
4. Allow switching between alternatives

Code trumps theory though, in-the-trenches-dev trumps armchair-dev. Don't let me slow you down at this juncture :)

**Comment by bayprogrammer** [comment]
Okay, the core questions is what language to use at this point. It sounds like our intersecting interests are: JavaScript, Python, Go.

Do you have a strong preference from amongst those three?

Let's write some code! :)

**Comment by DonnieWest** [comment]
No strong preference, but ranking them would give you:

1. Javascript - It's what I'm currently learning
2. Python - I'm familiar with it and already have tooling in place to use it. I'm somewhat interested in learning Python 3 though and it would ensure our project is future proof
3. Go - Interested in learning, but not so much at this particular juncture

**Comment by bayprogrammer** [comment]
Okay, I'm going to start hacking with Python and JavaScript for Glavo then. We'll see where things go from there! :)
