### ISSUE TITLE
cleaning house

### ISSUE THREAD

**Issue by bayprogrammer** [glavo-project/glavo#4]
@DonnieWest I'm trying to clean up stuff and narrow my focus better. I don't want to give up the idea of Glavo, but I don't think I'm going to be getting back to this vision of it any time soon. Might hack on something along the same lines in the future (and if I do you'll be of the first to know). Until then, do you object if I close down this organization and delete the repos? Don't want to leave vapourware sitting around unless I plan to act on it in the near-term.

**Comment by DonnieWest** [comment]
Go ahead and shut it down :+1:
